__default__:
  job-name: "{rule}"
  partition: short
  time: 1440
  gpu: gpu:0
  nodes: 1
  ntasks-per-node: 16
  mem: 32gb
  output: '~/CSCI_4118/Group-6-Metagenomic-Pipeline/err/{rule}.out' 
  error: '/Users/brne3762/CSCI_4118/Group-6-Metagenomic-Pipeline/err/{rule}.err'

model:
  partition: nvidia-a100
  nodelist: fijigpu-06
  gpu: gpu:1
  time: 1440