__default__:
  job-name: "{rule}"
  partition: short
  time: 1440
  gpu: gpu:0
  nodes: 1
  ntasks-per-node: 16
  mem: 32gb
  output: '"$MAIN}"/err/{rule}.out' 
  error: '"{$MAIN}"/err/{rule}.err' # not sure whether this main will work

model:
  partition: nvidia-a100
  nodelist: fijigpu-06
  gpu: gpu:1
  time: 1440
