name: Functional Tests

on:
  pull_request:
    branches: [main]

jobs:  
  run_functional_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v2
      - uses: mamba-org/setup-micromamba@v1
      - run: |
         cd test/Functional_tests
         bash test.sh
