name: Pycodestyle

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run_pycodestyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pycodestyle

      - name: Run pycodestyle
        run: |
          cd /src
          pycodestyle download_test_data.py sample_names.py
