name: Pycodestyle

on:
  pull_request:
    branches: [main]

jobs:
  run_pycodestyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pycodestyle

      - name: Change to src directory and run pycodestyle
        run: | 
          cd src
          pycodestyle sample_names.py
          pycodestyle download_test_data.py
