name: Unit/Functional/Pycodestyle Tests

on:
  pull_request:
    branches: [main]

jobs:  
  run_unit_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v2
      - uses: mamba-org/setup-micromamba@v1
      - run: |
         cd test/Unit_test
         python -m unittest test
         
  run_pycodestyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pycodestyle
      - name: Change to src directory and run pycodestyle
        run: | 
          cd src
          pycodestyle sample_names.py
          pycodestyle download_test_data.py
          
  run_functional_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v2
      - uses: mamba-org/setup-micromamba@v1
      - run: |
         cd test/Functional_test
         bash test.sh
