name: Unit Tests

on:
  pull_request:
    branches: [main]

jobs:  
  run_unit_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v2
      - uses: mamba-org/setup-micromamba@v1
      - run: |
         cd ../test/Unit_test
         python -m unittest test_my_utils
